version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: liquidart
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    depends_on:
      - 'graphql-engine'
      - 'minio'
    ports:
      - '3400:3000'
    environment:
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: liquidart
      REGISTRATION_CUSTOM_FIELDS: username,full_name
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: "true"
      STORAGE_ENABLE: "true"
      S3_ENDPOINT: http://minio:9000
      S3_SSL_ENABLED: "false"
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID:-minio_access_key}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:-liquidart}' ## min 8 character
  minio:
    image: minio/minio
    restart: always
    volumes:
      - ${STORAGE_DIR}:/export
    ports:
      - 9000:9000
    environment:
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      MINIO_ACCESS_KEY: '${S3_ACCESS_KEY_ID:-minio_access_key}' ## min 8 character
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:-liquidart}' ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/$${S3_BUCKET:-hasura-backend-plus} && /usr/bin/minio server /export'"
  bitcoin:
    image: vulpemventures/bitcoin:latest
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:19000
      - ${BITCOIN_NODE_PORT}:19001
    volumes:
      - ./liquidregtest/config/:/config
    restart: unless-stopped
  liquid:
    image: asoltys/liquid:latest
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
      - ${LIQUID_BLOCK_PORT}:18602
      - ${LIQUID_TX_PORT}:18603
    volumes:
      - ./liquidregtest/liquid-config/:/config
    restart: unless-stopped
  # Block explorer REST servers
  electrs:
    image: vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:19001
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - bitcoin
    ports:
      - ${BITCOIN_ELECTRS_RPC_PORT}:60401
      - ${BITCOIN_ELECTRS_PORT}:3002
    volumes:
      - ./liquidregtest/config/:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./liquidregtest/liquid-config/:/config
    restart: unless-stopped
  la-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: la-server
    ports:
      - 3939:3939
    volumes:
      - ./server:/app
  chopsticks:
    image: vulpemventures/nigiri-chopsticks:latest
    container_name: chopsticks
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - bitcoin:19001
      - --electrs-addr
      - electrs:3002
      - --addr
      - 0.0.0.0:3000
    depends_on:
      - bitcoin
      - electrs
    ports:
      - ${BITCOIN_CHOPSTICKS_PORT}:3000
    restart: unless-stopped
  chopsticks-liquid:
    image: vulpemventures/nigiri-chopsticks:latest
    container_name: chopsticks-liquid
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - liquid:18884
      - --electrs-addr
      - electrs-liquid:3002
      - --addr
      - 0.0.0.0:3000
      - --chain
      - liquid
    depends_on:
      - liquid
      - electrs-liquid
    ports:
      - ${LIQUID_CHOPSTICKS_PORT}:3000
    restart: unless-stopped
