version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: liquidart
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    depends_on:
      - 'graphql-engine'
      - 'minio'
    ports:
      - '3400:3000'
    environment:
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: liquidart
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: "true"
      STORAGE_ENABLE: "true"
      S3_ENDPOINT: http://minio:9000
      S3_SSL_ENABLED: "false"
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID:-minio_access_key}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:-liquidart}' ## min 8 character
  minio:
    image: minio/minio
    restart: always
    volumes:
      - 'minio_data:/data'
    ports:
      - '9000:9000'
    environment:
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      MINIO_ACCESS_KEY: '${S3_ACCESS_KEY_ID:-minio_access_key}' ## min 8 character
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:-liquidart}' ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/$${S3_BUCKET:-hasura-backend-plus} && /usr/bin/minio server /export'"
volumes:
  db_data:
  minio_data:
